### ISSUE TITLE
关于log_df和session_df时间排序rk的问题

### ISSUE THREAD

**Issue by zjpf** [fengtong-xiao/DMBGN#1]
1. log_df时间排序问题：
代码：q1 = "select *, ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY voucher_collect_time ASC) as rk from {logdf}".format(logdf="log_df")
log_df = ps.sqldf(q1, locals())
使用的是voucher_collect_time的字符串排序，而非数字排序
2. session_df中rk和action_time排序有差异
如选session_id=6777_314时：
983372,1,6777_314,314,199,30,99368,55161,order,aft,1,100722,4113,101441,1.0
983373,1,6777_314,314,199,30,99368,105402,order,aft,2,106784,6966,99361,4.0
983374,1,6777_314,314,199,30,99368,60529,order,aft,3,106806,4117,56645,3.0
983375,1,6777_314,314,199,30,99368,124268,order,aft,4,106807,8989,85140,2.0
983376,1,6777_314,314,199,30,99368,149035,order,aft,5,106807,14451,99361,
983377,1,6777_314,314,199,30,99368,105409,order,aft,6,106807,8975,99361,4.0
983378,1,6777_314,314,199,30,99368,147303,order,aft,7,107227,12284,56645,2.0
983379,1,6777_314,314,199,30,99368,41904,order,aft,8,108025,5891,126072,3.0
983380,1,6777_314,314,199,30,99368,19501,order,aft,9,109614,10100179,56645,3.0
983381,1,6777_314,314,199,30,99368,83839,order,aft,10,117892,12033,103322,1.0
983382,1,6777_314,314,199,30,99368,126274,order,aft,11,119693,13457,56645,4.0
983383,1,6777_314,314,199,30,99368,63166,order,aft,12,120140,13456,56645,2.0
983384,1,6777_314,314,199,30,99368,55415,order,aft,13,122646,12003,56645,2.0
983386,1,6777_314,314,199,30,99368,159734,order,aft,**15**,124508,7232,129454,5.0
983385,1,6777_314,314,199,30,99368,55148,order,aft,**14**,124527,4113,101441,1.0
983387,1,6777_314,314,199,30,99368,136254,order,aft,16,124553,14451,129454,
983388,1,6777_314,314,199,30,99368,159734,order,aft,17,124553,7232,129454,5.0
983389,1,6777_314,314,199,30,99368,119064,order,aft,18,124711,4307,267730,7.0
983390,1,6777_314,314,199,30,99368,90041,order,aft,19,124938,5493,56645,3.0
983391,1,6777_314,314,199,30,99368,119064,order,aft,20,124948,4307,267730,7.0

**Comment by fengtong-xiao** [comment]
Hi zjpf,

Thanks for your interest in our work!

#1:
Yes, this is a mistake made when we prepare this public code. Previously voucher_collect_time is Datetime data type instead of String and do not have such issue. We have updated the script DMBGN_SIGKDD21-release.ipython and rerun the experiment. You can have a look at the updated script, the results do not differ much and the conclusion remains.

Please note that the experiments from original paper do not have such issue as we prepared the user_voucher_log table in a different script directly from our database. 

Actually, what was affected is only the construction of historical UVG sequence, which was not in its chronological order. But this does not impact the final prediction much since the attention network will learn the importance weight of each historical input, and its order is less important. Those users with very rich redemption history will be affected more, nonetheless those sessions still belong to the same user. What matters is the aggregated information learnt from the historical behaviors.

#2:
The rk seems consistent with action_time in those data you shared, where as action_time increases, the rk increases as well.
